parameters:
  name: ''
  displayName: ''
  platform: ''

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Debug:
        configuration: Debug
      Release:
        configuration: Release
  steps:
  - checkout: self
    submodules: recursive
  - template: azure-pipelines-steps-linkedvdk.yml
  - script: 3rdParty\udcore\bin\premake-bin\premake5.exe vs2019 --os=android
    displayName: 'Run Premake'
  - task: MSBuild@1
    displayName: 'Build Projects'
    inputs:
      solution: udStream.sln
      platform: ${{ parameters.platform }}
      configuration: $(configuration)
      maximumCpuCount: true
      msbuildArguments: '/v:m'
  - publish: buildscripts/android/bin/${{ parameters.platform }}/Release/udStreamApp.apk
    displayName: 'Public Artifacts'
    condition: and(succeeded(), eq(variables['configuration'], 'Release'))
    artifact: ${{ parameters.name }}$(configuration)
